ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_USER_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_USER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_IMPERSONATION_STARTED';
