-- PostgreSQL requires new enum values to be committed before a later migration can use them.
CREATE TYPE "AiImageLanguage" AS ENUM ('UZBEK', 'RUSSIAN');

ALTER TYPE "AiAutomationStatus" ADD VALUE 'PRODUCT_DRAFT';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'RESEARCH_READY';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'RESEARCH_FAILED';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'WAITING_FOR_LISTING_APPROVAL';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'LISTING_READY';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'LISTING_FAILED';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'WAITING_FOR_IMAGE_IDEAS_APPROVAL';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'ANALYZING_COMPETITOR_IMAGES';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'IMAGE_IDEAS_READY';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'IMAGE_IDEAS_FAILED';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'WAITING_FOR_IMAGE_LANGUAGE_AND_CONFIRMATION';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'IMAGES_READY';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'IMAGES_FAILED';
ALTER TYPE "AiAutomationStatus" ADD VALUE 'CANCELLED';
ALTER TYPE "AiJobStepStatus" ADD VALUE 'CANCELLED';
